name: 'Use Terraform Action'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    # debug for service principal 
    # - name: Azure Login
    #   run: |
    #     az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    #     az storage blob list --account-name tfstatestore12345 --container-name tfstatecontainer

      
    # debug for pathing
    # - name: List directory contents
    #   run: ls -al ./vnet
    

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2


    - name: Terraform Deploy to Azure
      uses: MKTHEPLUGG/deploy-tf-vrs@1.0.7
      # these vars are for azurerm providor to auth with azure via SP we setup to deploy infra
      env:
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # debug for TF
      # env:
      #   TF_LOG: DEBUG
      with:
        # these vars are for the storage account authentication, we use the same sp as above
        storage_account_name: 'tfstatestore12345'
        container_name: tfstatecontainer
        key: 'terraform.tfstate'
        resource_group_name: TerraformStateRG
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        working_directory: './aks'
        # specify working directory to choose where you want to deploy from